title: 10k
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://columbine.space" # the base hostname & protocol for your site
exclude: [dummy]

# Staticman
staticman:
 allowedFields: ['name', 'title', 'description', 'location']
 branch: master
 commitMessage: "New piece of news."
 filename: "entry{@timestamp}"
 format: yml
 moderation: false
 path: "_data/reviews"
 requiredFields: ['name', 'title', 'description']
